apiVersion: v1
kind: Service
metadata:
  name: hellopython-service
spec:
  selector:
    app: hello-python
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30007
  type: NodePort
